### PR TITLE
[TOR-2924] Update margin top on notification banner

### PR DESCRIPTION
**Pull request by danasevcik**
**JIRA** - [TOR-2924](https://torchdental.atlassian.net/browse/TOR-2924)

**Description**
Update styling on notification banner

**Notes**

- Update margin top on PPE notification banner if it is not the first child element on the page.
- Desktop photo in the ticket shows less space between the checklist and PPE banners.

### CODE REVIEW

**Comment by pyen** [comment]
@danasevcik Apologies for the confusing state of affairs in `torchbrand` but the `dist/` tree contains only build artifacts, which are committed to git primarily for ease-of-use when referenced by the `torchweb` repository.

The source for changes to `dist/` is unsurprisingly in the `src/` tree, and it looks like those changes aren't in this PR? Probably from `src/sass/components/_notification.scss` ?

**Comment by danasevcik** [comment]
@pyen Understood - I removed the change from dist and added to the src file.

**Comment by pyen** [comment]
@danasevcik  Apologies again, it should be both. Contents of `src/` are built to `dist/` via `npm run build-css` (or `npm run start`), but we do need both.

If we commit `dist` without `src` then the next changes to `src` will overwrite `dist`.
If we commit `src` without `dist` then `torchweb` will not see the changes

**Comment by danasevcik** [comment]
@pyen Now understood!

**Review by pyen — APPROVED** [review]
:+1:

**Pull request merged**
